# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['mgf_filter', 'mgf_filter.cython']

package_data = \
{'': ['*']}

install_requires = \
['blist>=1.3.6,<2.0.0',
 'cython>=0.29.15,<0.30.0',
 'lxml>=4.5,<5.0',
 'numpy>=1.18,<2.0',
 'pyteomics>=4.2,<5.0']


setup_kwargs = {
    'name': 'mgf-filter',
    'version': '1.0.0',
    'description': '',
    'long_description': None,
    'author': 'Tobias Schmidt',
    'author_email': 'tobias.k.schmidt@tum.de',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.6,<4.0',
    'scripts': ['bin/MasterSpectrum']
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
